version: "3"

services:

  service.config:
    build: ./service.config
    image: test-config
    volumes:
      - ./service.config:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 7001:80
    expose: 
      - "80"
    command: npm start

  service.registry.device:
    build: ./service.registry.device/
    image: restful-home-service-device-registry
    volumes:
      - ./service.registry.device:/usr/src/app
    ports:
      - 7002:80

  service.controller.hue:
    build: ./service.controller.hue/
    image: restful-home-service-controller-hue
    volumes:
      - ./service.controller.hue:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 7003:80
    expose: 
      - "80"
    command: npm start

  web.client:
    build: 
      context: ./web.client
      dockerfile: dev.dockerfile
    image: restful-home-web-client
    volumes:
      - ./web.client:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 7000:8080
    env_file:
      - ./.env

    depends_on: # need this one here or no?
      - service.config
  