base:
  apiGateway: http://service.api-gateweay
  redis:
    host: redis
    port: 6379

service.registry.device:
  database: /devices.db

service.controller.hue:
  hueBridge:
    hostGateway: http://192.168.1.15
    hostName: laPyLGIKgtCfZ4jRDwJRhbTPoiwHxl-WBxu-ZT5l

unicorn:
  skrrt: "Missing unicorn: If you find it, you are probably high!"

  